export const colors = {
    WHITE: '#FFFFFF',
    LOTION: '#FCFCFC',
    ROMAN_SILVER: '#808191',
    BRIGHT_GRAY: '#E4E8EF',
    AZUREISH_WHITE: '#DADEFA',
    ROYAL_BLUE: '#475BE8',
    PALATINATE_BLUE: '#1E36E8',
    COLUMBIA_BLUE: '#C4E8EF',
    LAVENDER_BLUE: '#CFC8FF',
    EERIE_BLACK: '#11142D',
    PHILIPPINE_GRAY: "#919191",
    UFO_GREEN: "#2ED480"
}